# Generated by Django 3.1 on 2020-08-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesoMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('icon', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='accesoSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('uri', models.TextField()),
                ('idMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.accesomenus')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='', max_length=50)),
                ('apeido', models.TextField(default='', max_length=80)),
                ('apodo', models.TextField(default='', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='registreSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('token', models.TextField(verbose_name='token')),
                ('status', models.BooleanField(default=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.usuariosesion')),
            ],
        ),
        migrations.CreateModel(
            name='passwordUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modificAt', models.DateTimeField(auto_now_add=True, verbose_name='modific')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.usuariosesion')),
            ],
        ),
        migrations.CreateModel(
            name='accesoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso', models.BooleanField(default=False)),
                ('idAcceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.accesosubmenu')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesion.usuariosesion')),
            ],
        ),
    ]
