# Generated by Django 3.1 on 2020-08-22 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('costo', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('ingredientes', models.TextField(max_length=200, verbose_name='ingredientes')),
                ('preparacion', models.TextField(max_length=200, verbose_name='preparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('descripcions', models.TextField(max_length=200, verbose_name='descripcion')),
                ('total', models.IntegerField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemstore')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
