# Generated by Django 3.1 on 2020-08-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200824_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstore',
            name='nombre',
            field=models.TextField(default='', max_length=100, verbose_name='descripcion'),
        ),
    ]
