# Generated by Django 3.1 on 2020-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_itemstore_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstore',
            name='image',
            field=models.TextField(default='', verbose_name='image'),
        ),
    ]
