# Generated by Django 3.1 on 2020-09-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_itemstore_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idItem', models.IntegerField()),
                ('idClase', models.IntegerField()),
            ],
        ),
    ]
