# Generated by Django 3.1 on 2020-09-12 04:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_clasificacion_clasificacionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='image',
            field=models.TextField(default=''),
        ),
        
    ]
